services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '${EXTERNAL_DB_PORT}:3306'
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          '127.0.0.1',
          '-uroot',
          '-p${DB_ROOT_PASSWORD}',
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: ${API_PORT}
      DATABASE_URL: 'mysql://root:${DB_ROOT_PASSWORD}@db:3306/${DB_NAME}?schema=public'
      SECRET_KEY: ${SECRET_KEY}
      CLIENT_URL: ${CLIENT_URL}
    ports:
      - '${EXTERNAL_API_PORT}:8000'
    restart: always

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_BASE_API_URL: ${PUBLIC_API_URL} # ← map, bukan list
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_BASE_API_URL: ${PUBLIC_API_URL}
      NODE_ENV: production
    ports:
      - '${EXTERNAL_WEB_PORT}:3000'
    restart: always

volumes:
  db_data:
